/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        background: '#f8f9fa',
        surface: '#f8f9fa',
        'surface-bright': '#f8f9fa',
        'surface-dim': '#d9dadb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'surface-variant': '#e1e3e4',
        'on-surface': '#191c1d',
        'on-surface-variant': '#44474e',
        'on-background': '#191c1d',
        outline: '#74777f',
        'outline-variant': '#c4c6cf',
        primary: '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#001b3d',
        'on-primary-container': '#6f84ac',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#b1c7f2',
        secondary: '#725c00',
        'on-secondary': '#ffffff',
        'secondary-container': '#fed000',
        'on-secondary-container': '#6f5900',
        'secondary-fixed': '#ffe07f',
        'secondary-fixed-dim': '#edc200',
        tertiary: '#000000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#141b2c',
        'on-tertiary-container': '#7c8399',
        'tertiary-fixed': '#dbe2fa',
        'tertiary-fixed-dim': '#bfc6dd',
        'on-tertiary-fixed': '#141b2c',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
      },
      fontFamily: {
        display: ['Lexend', 'system-ui', 'sans-serif'],
        headline: ['Lexend', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['clamp(40px, 7vw, 64px)', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['clamp(28px, 4.5vw, 40px)', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['clamp(22px, 3vw, 32px)', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '1.2', fontWeight: '700' }],
        button: ['16px', { lineHeight: '1', letterSpacing: '0.01em', fontWeight: '600' }],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
      },
      spacing: {
        base: '8px',
        gutter: '24px',
        'stack-sm': '12px',
        'stack-md': '24px',
        'stack-lg': '48px',
        'section-padding': '80px',
      },
      maxWidth: {
        container: '1280px',
      },
      boxShadow: {
        ambient: '0 32px 64px -12px rgba(0, 27, 61, 0.12)',
        glow: '0 0 80px -10px rgba(0, 27, 61, 0.35)',
      },
      keyframes: {
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.96)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
      animation: {
        'fade-up': 'fade-up 0.7s ease-out both',
        'fade-in': 'fade-in 0.8s ease-out both',
        'scale-in': 'scale-in 0.7s ease-out both',
        float: 'float 6s ease-in-out infinite',
        shimmer: 'shimmer 3s linear infinite',
      },
    },
  },
  plugins: [],
};
